// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/mime;

# Public REST API for Jira Service Management
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://your-domain.atlassian.net") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Get assets workspaces
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returned if the request is successful 
    remote isolated function getAssetsWorkspaces(map<string|string[]> headers = {}, *GetAssetsWorkspacesQueries queries) returns PagedDTOAssetsWorkspaceDTO|error {
        string resourcePath = string `/rest/servicedeskapi/assets/workspace`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create customer
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Email address and display name of the customer to create 
    # + return - Returns the customer details 
    remote isolated function createCustomer(CustomerCreateDTO payload, map<string|string[]> headers = {}, *CreateCustomerQueries queries) returns UserDTO|error {
        string resourcePath = string `/rest/servicedeskapi/customer`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Create customer without permission check
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - JSON body containing the email address and display name of the customer to create 
    # + return - Returns the created customer 
    remote isolated function createCustomerSkipPermissionCheck(CustomerCreateDTO payload, map<string|string[]> headers = {}, *CreateCustomerSkipPermissionCheckQueries queries) returns UserDTO|error {
        string resourcePath = string `/rest/servicedeskapi/customer/skip-permission-check`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Revoke portal only access for user
    #
    # + accountId - The account ID of the user, which uniquely identifies the portal-only account. For example, *qm:a713c8ea-1075-4e30-9d96-891a7d181739:5ad6d3581db05e2a66fa80b*
    # + headers - Headers to be sent with the request 
    # + return - Returned if the request is successful 
    remote isolated function revokePortalOnlyAccessForUser(string accountId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/customer/user/${getEncodedUri(accountId)}/revoke-portal-only-access`;
        http:Request request = new;
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Get Jira Service Management instance info
    #
    # + headers - Headers to be sent with the request 
    # + return - Returns the runtime information for the Jira Service Management instance 
    remote isolated function getInfo(map<string|string[]> headers = {}) returns SoftwareInfoDTO|error {
        string resourcePath = string `/rest/servicedeskapi/info`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get insight workspaces
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns a page of Insight workspace IDs 
    remote isolated function getInsightWorkspaces(map<string|string[]> headers = {}, *GetInsightWorkspacesQueries queries) returns PagedDTOInsightWorkspaceDTO|error {
        string resourcePath = string `/rest/servicedeskapi/insight/workspace`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get articles
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the articles, on the specified page of the results 
    remote isolated function getArticles(map<string|string[]> headers = {}, *GetArticlesQueries queries) returns PagedDTOArticleDTO|error {
        string resourcePath = string `/rest/servicedeskapi/knowledgebase/article`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # View knowledge base article
    #
    # + pageId - The ID of the knowledge base article page
    # + headers - Headers to be sent with the request 
    # + return - Returns the rendered content of the article 
    remote isolated function viewArticle(int pageId, map<string|string[]> headers = {}) returns string|error {
        string resourcePath = string `/rest/servicedeskapi/knowledgebase/article/view/${getEncodedUri(pageId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get organizations
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns paginated list of organizations 
    remote isolated function getOrganizations(map<string|string[]> headers = {}, *GetOrganizationsQueries queries) returns PagedDTOOrganizationDTO|error {
        string resourcePath = string `/rest/servicedeskapi/organization`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create organization
    #
    # + headers - Headers to be sent with the request 
    # + payload - Name of the organization to create 
    # + return - Returns the created organization or the existing organization if name already exists 
    remote isolated function createOrganization(OrganizationCreateDTO payload, map<string|string[]> headers = {}) returns OrganizationDTO|error {
        string resourcePath = string `/rest/servicedeskapi/organization`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get organization
    #
    # + organizationId - The ID of the organization
    # + headers - Headers to be sent with the request 
    # + return - Returns the requested organization 
    remote isolated function getOrganization(int:Signed32 organizationId, map<string|string[]> headers = {}) returns OrganizationDTO|error {
        string resourcePath = string `/rest/servicedeskapi/organization/${getEncodedUri(organizationId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete organization
    #
    # + organizationId - The ID of the organization
    # + headers - Headers to be sent with the request 
    # + return - Returned if the organization was deleted 
    remote isolated function deleteOrganization(int:Signed32 organizationId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/organization/${getEncodedUri(organizationId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get organization property keys
    #
    # + organizationId - The ID of the organization from which keys will be returned
    # + headers - Headers to be sent with the request 
    # + return - Returned if the organization was found 
    remote isolated function getPropertiesKeys(string organizationId, map<string|string[]> headers = {}) returns PropertyKeys|error {
        string resourcePath = string `/rest/servicedeskapi/organization/${getEncodedUri(organizationId)}/property`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get organization property
    #
    # + organizationId - The ID of the organization from which the property will be returned
    # + propertyKey - The key of the property to return
    # + headers - Headers to be sent with the request 
    # + return - Returns the organization's property 
    remote isolated function getProperty(string organizationId, string propertyKey, map<string|string[]> headers = {}) returns EntityProperty|error {
        string resourcePath = string `/rest/servicedeskapi/organization/${getEncodedUri(organizationId)}/property/${getEncodedUri(propertyKey)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Set organization property
    #
    # + organizationId - The ID of the organization on which the property will be set
    # + propertyKey - The key of the organization's property. The maximum length of the key is 255 bytes
    # + headers - Headers to be sent with the request 
    # + payload - The value of the property. The value has to be a valid, non-empty [JSON](https://tools.ietf.org/html/rfc4627) value. The maximum length of the property value is 32768 bytes 
    # + return - Returned if the organization property was updated 
    remote isolated function setProperty(string organizationId, string propertyKey, json payload, map<string|string[]> headers = {}) returns json|error {
        string resourcePath = string `/rest/servicedeskapi/organization/${getEncodedUri(organizationId)}/property/${getEncodedUri(propertyKey)}`;
        http:Request request = new;
        request.setPayload(payload, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Delete organization property
    #
    # + organizationId - The ID of the organization from which the property will be removed
    # + propertyKey - The key of the property to remove
    # + headers - Headers to be sent with the request 
    # + return - Returned if the organization property was removed 
    remote isolated function deleteProperty(string organizationId, string propertyKey, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/organization/${getEncodedUri(organizationId)}/property/${getEncodedUri(propertyKey)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get users in organization
    #
    # + organizationId - The ID of the organization
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns a paged list of users associated with the organization, ordered by their accountId 
    remote isolated function getUsersInOrganization(int:Signed32 organizationId, map<string|string[]> headers = {}, *GetUsersInOrganizationQueries queries) returns PagedDTOUserDTO|error {
        string resourcePath = string `/rest/servicedeskapi/organization/${getEncodedUri(organizationId)}/user`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Add users to organization
    #
    # + organizationId - The ID of the organization
    # + headers - Headers to be sent with the request 
    # + payload - Account IDs of the users to add to the organization 
    # + return - Returned if all the users were valid and added to the organization, no response payload is provided 
    remote isolated function addUsersToOrganization(int:Signed32 organizationId, UsersOrganizationUpdateDTO payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/organization/${getEncodedUri(organizationId)}/user`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Remove users from organization
    #
    # + organizationId - The ID of the organization
    # + headers - Headers to be sent with the request 
    # + payload - Account IDs of the users to remove from the organization 
    # + return - The request completed successfully. No additional content will be sent in the response 
    remote isolated function removeUsersFromOrganization(int:Signed32 organizationId, UsersOrganizationUpdateDTO payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/organization/${getEncodedUri(organizationId)}/user`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->delete(resourcePath, request, headers);
    }

    # Get customer requests
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the customer requests, on the specified page of the results 
    remote isolated function getCustomerRequests(map<string|string[]> headers = {}, *GetCustomerRequestsQueries queries) returns PagedDTOCustomerRequestDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request`;
        map<Encoding> queryParamEncoding = {"requestOwnership": {style: FORM, explode: true}, "expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create customer request
    #
    # + headers - Headers to be sent with the request 
    # + payload - Service desk, request type and field values of the customer request to create 
    # + return - Returned if the customer request was created 
    remote isolated function createCustomerRequest(RequestCreateDTO payload, map<string|string[]> headers = {}) returns CustomerRequestDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Validate customer request
    #
    # + headers - Headers to be sent with the request 
    # + payload - Service desk, request type and field values of the customer request to validate 
    # + return - Returned with the validation result. \{@code valid\} is true when the payload is valid 
    remote isolated function validateCustomerRequest(RequestCreateDTO payload, map<string|string[]> headers = {}) returns RequestValidationResultDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/validate`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get customer request by id or key
    #
    # + issueIdOrKey - The ID or Key of the customer request to be returned
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the customer request 
    remote isolated function getCustomerRequestByIdOrKey(string issueIdOrKey, map<string|string[]> headers = {}, *GetCustomerRequestByIdOrKeyQueries queries) returns CustomerRequestDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get approvals
    #
    # + issueIdOrKey - The ID or key of the customer request to be queried for its approvals
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the customer request's approvals 
    remote isolated function getApprovals(string issueIdOrKey, map<string|string[]> headers = {}, *GetApprovalsQueries queries) returns PagedDTOApprovalDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/approval`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get approval by id
    #
    # + issueIdOrKey - The ID or key of the customer request the approval is on
    # + approvalId - The ID of the approval to be returned
    # + headers - Headers to be sent with the request 
    # + return - Returns the requested approval 
    remote isolated function getApprovalById(string issueIdOrKey, int:Signed32 approvalId, map<string|string[]> headers = {}) returns ApprovalDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/approval/${getEncodedUri(approvalId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Answer approval
    #
    # + issueIdOrKey - The ID or key of the customer request to be updated
    # + approvalId - The ID of the approval to be updated
    # + headers - Headers to be sent with the request 
    # + payload - Approve or decline decision to record on the approval 
    # + return - Returns the updated approval 
    remote isolated function answerApproval(string issueIdOrKey, int:Signed32 approvalId, ApprovalDecisionRequestDTO payload, map<string|string[]> headers = {}) returns ApprovalDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/approval/${getEncodedUri(approvalId)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get attachments for request
    #
    # + issueIdOrKey - The ID or key of the customer request from which the attachments will be listed
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the visible attachments from the customer request 
    remote isolated function getAttachmentsForRequest(string issueIdOrKey, map<string|string[]> headers = {}, *GetAttachmentsForRequestQueries queries) returns PagedDTOAttachmentDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/attachment`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create comment with attachment
    #
    # + issueIdOrKey - The ID or key of the customer request to which the attachment will be added
    # + headers - Headers to be sent with the request 
    # + payload - Temporary attachment IDs to attach, their visibility and an optional comment 
    # + return - Returns the attachments and comment 
    remote isolated function createAttachment(string issueIdOrKey, AttachmentCreateDTO payload, map<string|string[]> headers = {}) returns AttachmentCreateResultDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/attachment`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get attachment content
    #
    # + issueIdOrKey - The ID or key for the customer request the attachment is associated with
    # + attachmentId - The ID for the attachment
    # + headers - Headers to be sent with the request 
    # + return - The attachment content 
    remote isolated function getAttachmentContent(string issueIdOrKey, int attachmentId, map<string|string[]> headers = {}) returns byte[]|error? {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/attachment/${getEncodedUri(attachmentId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get attachment thumbnail
    #
    # + issueIdOrKey - The ID or key for the customer request the attachment is associated with
    # + attachmentId - The ID of the attachment
    # + headers - Headers to be sent with the request 
    # + return - The attachment thumbnail image 
    remote isolated function getAttachmentThumbnail(string issueIdOrKey, int attachmentId, map<string|string[]> headers = {}) returns byte[]|error? {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/attachment/${getEncodedUri(attachmentId)}/thumbnail`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get request comments
    #
    # + issueIdOrKey - The ID or key of the customer request whose comments will be retrieved
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the comments, on the specified page of the results 
    remote isolated function getRequestComments(string issueIdOrKey, map<string|string[]> headers = {}, *GetRequestCommentsQueries queries) returns PagedDTOCommentDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/comment`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create request comment
    #
    # + issueIdOrKey - The ID or key of the customer request to which the comment will be added
    # + headers - Headers to be sent with the request 
    # + payload - Body and visibility of the comment to add to the request 
    # + return - Returns the comment 
    remote isolated function createRequestComment(string issueIdOrKey, CommentCreateDTO payload, map<string|string[]> headers = {}) returns CommentDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/comment`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get request comment by id
    #
    # + issueIdOrKey - The ID or key of the customer request that contains the comment
    # + commentId - The ID of the comment to retrieve
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the comment 
    remote isolated function getRequestCommentById(string issueIdOrKey, int commentId, map<string|string[]> headers = {}, *GetRequestCommentByIdQueries queries) returns CommentDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/comment/${getEncodedUri(commentId)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get comment attachments
    #
    # + issueIdOrKey - The ID or key of the customer request that contains the comment
    # + commentId - The ID of the comment
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the attachments, on the specified page of the results 
    remote isolated function getCommentAttachments(string issueIdOrKey, int commentId, map<string|string[]> headers = {}, *GetCommentAttachmentsQueries queries) returns PagedDTOAttachmentDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/comment/${getEncodedUri(commentId)}/attachment`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get subscription status
    #
    # + issueIdOrKey - The ID or key of the customer request to be queried for subscription status
    # + headers - Headers to be sent with the request 
    # + return - Returns the status of the notification subscription 
    remote isolated function getSubscriptionStatus(string issueIdOrKey, map<string|string[]> headers = {}) returns RequestNotificationSubscriptionDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/notification`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Subscribe to request notifications
    #
    # + issueIdOrKey - The ID or key of the customer request to be subscribed to
    # + headers - Headers to be sent with the request 
    # + return - Returns if the user was subscribed 
    remote isolated function subscribe(string issueIdOrKey, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/notification`;
        http:Request request = new;
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Unsubscribe
    #
    # + issueIdOrKey - The ID or key of the customer request to be unsubscribed from
    # + headers - Headers to be sent with the request 
    # + return - Returns if the user was unsubscribed 
    remote isolated function unsubscribe(string issueIdOrKey, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/notification`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get request participants
    #
    # + issueIdOrKey - The ID or key of the customer request to be queried for its participants
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the customer request's participants, on the specified page of the results 
    remote isolated function getRequestParticipants(string issueIdOrKey, map<string|string[]> headers = {}, *GetRequestParticipantsQueries queries) returns PagedDTOUserDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/participant`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Add request participants
    #
    # + issueIdOrKey - The ID or key of the customer request to have participants added
    # + headers - Headers to be sent with the request 
    # + payload - Account IDs of the users to add as request participants 
    # + return - Returns the participants added to the customer request 
    remote isolated function addRequestParticipants(string issueIdOrKey, RequestParticipantUpdateDTO payload, map<string|string[]> headers = {}) returns PagedDTOUserDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/participant`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Remove request participants
    #
    # + issueIdOrKey - The ID or key of the customer request to have participants removed
    # + headers - Headers to be sent with the request 
    # + payload - Account IDs of the users to remove as request participants 
    # + return - Returns the first page of the customer request's participants (after removal of the users) 
    remote isolated function removeRequestParticipants(string issueIdOrKey, RequestParticipantUpdateDTO payload, map<string|string[]> headers = {}) returns PagedDTOUserDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/participant`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->delete(resourcePath, request, headers);
    }

    # Get sla information
    #
    # + issueIdOrKey - The ID or key of the customer request whose SLAs will be retrieved
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the SLA records on the customer request, on the specified page of the results 
    remote isolated function getSlaInformation(string issueIdOrKey, map<string|string[]> headers = {}, *GetSlaInformationQueries queries) returns PagedDTOSlaInformationDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/sla`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get sla information by id
    #
    # + issueIdOrKey - The ID or key of the customer request whose SLAs will be retrieved
    # + slaMetricId - The ID or key of the SLAs metric to be retrieved
    # + headers - Headers to be sent with the request 
    # + return - Returns the SLA record, on the specified page of the results 
    remote isolated function getSlaInformationById(string issueIdOrKey, int slaMetricId, map<string|string[]> headers = {}) returns SlaInformationDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/sla/${getEncodedUri(slaMetricId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get customer request status
    #
    # + issueIdOrKey - The ID or key of the customer request to be retrieved
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the customer request's status history, on the specified page of the results 
    remote isolated function getCustomerRequestStatus(string issueIdOrKey, map<string|string[]> headers = {}, *GetCustomerRequestStatusQueries queries) returns PagedDTOCustomerRequestStatusDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/status`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get customer transitions
    #
    # + issueIdOrKey - The ID or key of the customer request whose transitions will be retrieved
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the transitions available to the user on the customer request 
    remote isolated function getCustomerTransitions(string issueIdOrKey, map<string|string[]> headers = {}, *GetCustomerTransitionsQueries queries) returns PagedDTOCustomerTransitionDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/transition`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Perform customer transition
    #
    # + issueIdOrKey - ID or key of the issue to transition
    # + headers - Headers to be sent with the request 
    # + payload - ID of the transition to perform and an optional comment 
    # + return - Returned if the request is transitioned 
    remote isolated function performCustomerTransition(string issueIdOrKey, CustomerTransitionExecutionDTO payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(issueIdOrKey)}/transition`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get feedback
    #
    # + requestIdOrKey - The id or the key of the request to post the feedback on
    # + headers - Headers to be sent with the request 
    # + return - Returns the comment 
    remote isolated function getFeedback(string requestIdOrKey, map<string|string[]> headers = {}) returns CSATFeedbackFullDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(requestIdOrKey)}/feedback`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Post feedback
    #
    # + requestIdOrKey - The id or the key of the request to post the feedback on
    # + headers - Headers to be sent with the request 
    # + payload - The feedback to be added on the request 
    # + return - Returns the comment 
    remote isolated function postFeedback(string requestIdOrKey, CSATFeedbackFullDTO payload, map<string|string[]> headers = {}) returns CSATFeedbackFullDTO|error {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(requestIdOrKey)}/feedback`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Delete feedback
    #
    # + requestIdOrKey - The id or the key of the request to post the feedback on
    # + headers - Headers to be sent with the request 
    # + return - No content 
    remote isolated function deleteFeedback(string requestIdOrKey, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/request/${getEncodedUri(requestIdOrKey)}/feedback`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get all request types
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the request types, on the specified page of the results 
    remote isolated function getAllRequestTypes(map<string|string[]> headers = {}, *GetAllRequestTypesQueries queries) returns PagedDTORequestTypeDTO|error {
        string resourcePath = string `/rest/servicedeskapi/requesttype`;
        map<Encoding> queryParamEncoding = {"serviceDeskId": {style: FORM, explode: true}, "expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get service desks
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the service desks, on the specified page of the results 
    remote isolated function getServiceDesks(map<string|string[]> headers = {}, *GetServiceDesksQueries queries) returns PagedDTOServiceDeskDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get service desk by id
    #
    # + serviceDeskId - The ID of the service desk to return. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + return - Returns the requested service desk 
    remote isolated function getServiceDeskById(string serviceDeskId, map<string|string[]> headers = {}) returns ServiceDeskDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Attach temporary file
    #
    # + serviceDeskId - The ID of the Service Desk to which the file will be attached. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + payload - Files to upload as temporary attachments, as multipart form data 
    # + return - Returns if the file(s) were attached 
    remote isolated function attachTemporaryFile(string serviceDeskId, AttachTemporaryFileRequest payload, AttachTemporaryFileHeaders headers = {}) returns TemporaryAttachments|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/attachTemporaryFile`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(payload);
        request.setBodyParts(bodyParts);
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get customers
    #
    # + serviceDeskId - The ID of the service desk the customer list should be returned from. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the service desk's customer list 
    remote isolated function getCustomers(string serviceDeskId, map<string|string[]> headers = {}, *GetCustomersQueries queries) returns PagedDTOUserDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/customer`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Add customers
    #
    # + serviceDeskId - The ID of the service desk the customer list should be returned from. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + payload - Account IDs of the customers to add to the service desk 
    # + return - Returned if all the customers were added to the service desk or were already associated with the service desk 
    remote isolated function addCustomers(string serviceDeskId, ServiceDeskCustomerDTO payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/customer`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Remove customers
    #
    # + serviceDeskId - The ID of the service desk the customers should be removed from. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + payload - Account IDs of the customers to remove from the service desk 
    # + return - Returned if the customers were removed from the service desk, or any of the customers were not associated with the service desk 
    remote isolated function removeCustomers(string serviceDeskId, ServiceDeskCustomerDTO payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/customer`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->delete(resourcePath, request, headers);
    }

    # Invite customer
    #
    # + serviceDeskId - The ID of the service desk to which the newly created customer should be added
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + payload - Email address and display name of the customer to invite 
    # + return - Returns the customer details 
    remote isolated function inviteCustomer(string serviceDeskId, ServiceDeskCustomerInviteDTO payload, map<string|string[]> headers = {}, *InviteCustomerQueries queries) returns json|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/customer/invite`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Add customers without permission check
    #
    # + serviceDeskId - The ID of the service desk to add customers to. This can alternatively be a project identifier
    # + headers - Headers to be sent with the request 
    # + payload - JSON body containing the account IDs of customers to add 
    # + return - The request completed successfully. No additional content will be sent in the response 
    remote isolated function addCustomersSkipPermissionCheck(string serviceDeskId, ServiceDeskCustomerDTO payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/customer/skip-permission-check`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get articles of a service desk
    #
    # + serviceDeskId - The ID of the service desk
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the articles, on the specified page of the results 
    remote isolated function getArticlesByServiceDeskId(string serviceDeskId, map<string|string[]> headers = {}, *GetArticlesByServiceDeskIdQueries queries) returns PagedDTOArticleDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/knowledgebase/article`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get organizations of a service desk
    #
    # + serviceDeskId - The ID of the service desk from which the organization list will be returned. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the requested organizations list 
    remote isolated function getOrganizationsByServiceDeskId(string serviceDeskId, map<string|string[]> headers = {}, *GetOrganizationsByServiceDeskIdQueries queries) returns PagedDTOOrganizationDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/organization`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Add organization
    #
    # + serviceDeskId - The ID of the service desk to which the organization will be added. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + payload - ID of the organization to add to the service desk 
    # + return - Returned if the organization was added or the organization was already associated with the service desk 
    remote isolated function addOrganization(string serviceDeskId, OrganizationServiceDeskUpdateDTO payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/organization`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Remove organization
    #
    # + serviceDeskId - The ID of the service desk from which the organization will be removed. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + payload - ID of the organization to remove from the service desk 
    # + return - Returned if the organization was removed from the service desk or no such organization was associated with the service desk 
    remote isolated function removeOrganization(string serviceDeskId, OrganizationServiceDeskUpdateDTO payload, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/organization`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->delete(resourcePath, request, headers);
    }

    # Get queues
    #
    # + serviceDeskId - ID of the service desk whose queues will be returned. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the queues of the service desk, on the specified page of the results 
    remote isolated function getQueues(string serviceDeskId, map<string|string[]> headers = {}, *GetQueuesQueries queries) returns PagedDTOQueueDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/queue`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get a service desk queue
    #
    # + serviceDeskId - ID of the service desk whose queues will be returned. This can alternatively be a [project identifier.](#project-identifiers)
    # + queueId - ID of the required queue
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the specific queue of the service desk 
    remote isolated function getQueue(string serviceDeskId, int queueId, map<string|string[]> headers = {}, *GetQueueQueries queries) returns QueueDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/queue/${getEncodedUri(queueId)}`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get issues in queue
    #
    # + serviceDeskId - The ID of the service desk containing the queue to be queried. This can alternatively be a [project identifier.](#project-identifiers)
    # + queueId - The ID of the queue whose customer requests will be returned
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the customer requests belonging to the queue, on the specified page of the results 
    remote isolated function getIssuesInQueue(string serviceDeskId, int queueId, map<string|string[]> headers = {}, *GetIssuesInQueueQueries queries) returns PagedDTOIssueBean|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/queue/${getEncodedUri(queueId)}/issue`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get request types
    #
    # + serviceDeskId - The ID of the service desk whose customer request types are to be returned. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the requested customer request types, on the specified page of the results 
    remote isolated function getRequestTypes(string serviceDeskId, map<string|string[]> headers = {}, *GetRequestTypesQueries queries) returns PagedDTORequestTypeDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttype`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Create request type
    #
    # + serviceDeskId - The ID of the service desk where the customer request type is to be created. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + payload - Issue type, name and help text of the request type to create 
    # + return - Returns the customer request type created 
    remote isolated function createRequestType(string serviceDeskId, RequestTypeCreateDTO payload, map<string|string[]> headers = {}) returns RequestTypeDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttype`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Check request type permissions
    #
    # + serviceDeskId - The ID of the service desk
    # + headers - Headers to be sent with the request 
    # + payload - Details of the permissions to check 
    # + return - Returned if the request is successful 
    remote isolated function checkRequestTypePermissions(string serviceDeskId, RequestTypePermissionCheckRequestDTO payload, map<string|string[]> headers = {}) returns RequestTypePermissionCheckResponse|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttype/permissions/check`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Get request type by id
    #
    # + serviceDeskId - The ID of the service desk whose customer request type is to be returned. This can alternatively be a [project identifier.](#project-identifiers)
    # + requestTypeId - The ID of the customer request type to be returned
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the customer request type item 
    remote isolated function getRequestTypeById(string serviceDeskId, string requestTypeId, map<string|string[]> headers = {}, *GetRequestTypeByIdQueries queries) returns RequestTypeDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttype/${getEncodedUri(requestTypeId)}`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Delete request type
    #
    # + serviceDeskId - The ID or [project identifier](#project-identifiers) of the service desk
    # + requestTypeId - The ID of the request type
    # + headers - Headers to be sent with the request 
    # + return - Returned if the request type is deleted 
    remote isolated function deleteRequestType(string serviceDeskId, int:Signed32 requestTypeId, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttype/${getEncodedUri(requestTypeId)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get request type fields
    #
    # + serviceDeskId - The ID of the service desk containing the request types whose fields are to be returned. This can alternatively be a [project identifier.](#project-identifiers)
    # + requestTypeId - The ID of the request types whose fields are to be returned
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the request type's fields and user permission details, on the specified page of the results 
    remote isolated function getRequestTypeFields(string serviceDeskId, int:Signed32 requestTypeId, map<string|string[]> headers = {}, *GetRequestTypeFieldsQueries queries) returns CustomerRequestCreateMetaDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttype/${getEncodedUri(requestTypeId)}/field`;
        map<Encoding> queryParamEncoding = {"expand": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        return self.clientEp->get(resourcePath, headers);
    }

    # Get request type property keys
    #
    # + requestTypeId - The ID of the request type for which keys will be retrieved
    # + serviceDeskId - The ID of the service desk which contains the request type. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + return - Returned if the request type was found 
    remote isolated function getPropertiesKeysByServiceDeskId(int:Signed32 requestTypeId, string serviceDeskId, map<string|string[]> headers = {}) returns PropertyKeys|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttype/${getEncodedUri(requestTypeId)}/property`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Get request type property
    #
    # + serviceDeskId - The ID of the service desk which contains the request type. This can alternatively be a [project identifier.](#project-identifiers)
    # + requestTypeId - The ID of the request type from which the property will be retrieved
    # + propertyKey - The key of the property to return
    # + headers - Headers to be sent with the request 
    # + return - Returned if the request type property was returned 
    remote isolated function getPropertyByServiceDeskId(string serviceDeskId, int:Signed32 requestTypeId, string propertyKey, map<string|string[]> headers = {}) returns EntityProperty|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttype/${getEncodedUri(requestTypeId)}/property/${getEncodedUri(propertyKey)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Set request type property
    #
    # + serviceDeskId - The ID of the service desk which contains the request type. This can alternatively be a [project identifier.](#project-identifiers)
    # + requestTypeId - The ID of the request type on which the property will be set
    # + propertyKey - The key of the request type property. The maximum length of the key is 255 bytes
    # + headers - Headers to be sent with the request 
    # + payload - The value of the request type property. The value has to be a valid, non-empty [JSON](https://tools.ietf.org/html/rfc4627) value. The maximum length of the property value is 32768 bytes 
    # + return - Returned if the request type property is updated 
    remote isolated function setPropertyByServiceDeskId(string serviceDeskId, int:Signed32 requestTypeId, string propertyKey, json payload, map<string|string[]> headers = {}) returns json|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttype/${getEncodedUri(requestTypeId)}/property/${getEncodedUri(propertyKey)}`;
        http:Request request = new;
        request.setPayload(payload, "application/json");
        return self.clientEp->put(resourcePath, request, headers);
    }

    # Delete request type property
    #
    # + serviceDeskId - The ID of the service desk which contains the request type. This can alternatively be a [project identifier.](#project-identifiers)
    # + requestTypeId - The ID of the request type for which the property will be removed
    # + propertyKey - The key of the property to remove
    # + headers - Headers to be sent with the request 
    # + return - Returned if the request type property was removed 
    remote isolated function deletePropertyByServiceDeskId(string serviceDeskId, int:Signed32 requestTypeId, string propertyKey, map<string|string[]> headers = {}) returns error? {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttype/${getEncodedUri(requestTypeId)}/property/${getEncodedUri(propertyKey)}`;
        return self.clientEp->delete(resourcePath, headers = headers);
    }

    # Get request type groups
    #
    # + serviceDeskId - The ID of the service desk whose customer request type groups are to be returned. This can alternatively be a [project identifier.](#project-identifiers)
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the service desk's customer request type groups, on the specified page of the results 
    remote isolated function getRequestTypeGroups(string serviceDeskId, map<string|string[]> headers = {}, *GetRequestTypeGroupsQueries queries) returns PagedDTORequestTypeGroupDTO|error {
        string resourcePath = string `/rest/servicedeskapi/servicedesk/${getEncodedUri(serviceDeskId)}/requesttypegroup`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        return self.clientEp->get(resourcePath, headers);
    }
}
