// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/data.jsondata;
import ballerina/http;

# Actions the calling user can perform on a customer request
public type CustomerRequestActionsDTO record {|
    # Action of removing participants from a request
    CustomerRequestActionDTO removeParticipant?;
    # Action of adding participants to a request
    CustomerRequestActionDTO addParticipant?;
    # Action of adding attachments to a request
    CustomerRequestActionDTO addAttachment?;
    # Action of adding comments to a request
    CustomerRequestActionDTO addComment?;
|};

# A page of organization results
public type PagedDTOOrganizationDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    OrganizationDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Link to the REST resource itself
public type SelfLinkDTO record {|
    # URL of the resource
    string self?;
|};

# Users to add to or remove from an organization
public type UsersOrganizationUpdateDTO record {
    # List of customers, specific by account IDs, to add to or remove from the organization.
    string[] accountIds?;
    # The organizationId in which users need to be added
    int:Signed32 organizationId?;
    # This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. Use `accountIds` instead.
    string[] usernames?;
};

# Multipart form carrying the file to upload as a temporary attachment
public type AttachTemporaryFileRequest record {
    # The file to upload. The multipart field must be named `file`
    record {byte[] fileContent; string fileName;} file;
};

# Generic JSON value node as serialized by the Jira backend
public type JsonNode record {|
    # Node value as a double
    decimal valueAsDouble?;
    # Numeric type of the node
    "INT"|"LONG"|"BIG_INTEGER"|"FLOAT"|"DOUBLE"|"BIG_DECIMAL" numberType?;
    # Names of the fields of an object node
    record {} fieldNames?;
    # Node value as a decimal
    decimal decimalValue?;
    # Node value as a boolean
    boolean valueAsBoolean?;
    # Whether the node is a value node
    boolean valueNode?;
    # Whether the node holds a long
    boolean long?;
    # Node value as a long
    int longValue?;
    # Node value as an integer
    int:Signed32 valueAsInt?;
    # Whether the node is missing
    boolean missingNode?;
    # Whether the node holds a number
    boolean number?;
    # Node value as text
    string valueAsText?;
    # Whether the node is an array
    boolean array?;
    # Whether the node is a container node
    boolean containerNode?;
    # Numeric value of the node
    decimal numberValue?;
    # Whether the node holds a big decimal
    boolean bigDecimal?;
    # Node value as a long
    int valueAsLong?;
    # Whether the node holds an integral number
    boolean integralNumber?;
    # Text value of the node
    string textValue?;
    # Whether the node holds a double
    boolean double?;
    # Node value as an integer
    int:Signed32 intValue?;
    # Whether the node holds a big integer
    boolean bigInteger?;
    # Node value as a double
    decimal doubleValue?;
    # Whether the node holds a floating-point number
    boolean floatingPointNumber?;
    # Whether the node holds an integer
    boolean 'int?;
    # Whether the node holds text
    boolean textual?;
    # Whether the node wraps a plain Java object
    boolean pojo?;
    # Node value as a big integer
    int bigIntegerValue?;
    # Whether the node holds a boolean
    boolean 'boolean?;
    # Whether the node is null
    boolean 'null?;
    # Whether the node holds binary data
    boolean binary?;
    # Elements of an array node
    record {} elements?;
    # Boolean value of the node
    boolean booleanValue?;
    # Fields of an object node
    record {} fields?;
    # Binary value of the node
    string[] binaryValue?;
    # Whether the node is an object
    boolean 'object?;
|};

# Represents the Queries record for the operation: getRequestTypeFields
public type GetRequestTypeFieldsQueries record {
    # Use [expand](#expansion) to include additional information in the response. This parameter accepts `hiddenFields` that returns hidden fields associated with the request type
    string[] expand?;
};

# A date and time rendered in several formats
public type DateDTO record {|
    # Date in a user-friendly text format
    string friendly?;
    # Date in ISO8601 format
    string iso8601?;
    # Date as the number of milliseconds that have elapsed since 00:00:00 Coordinated Universal Time (UTC), 1 January 1970
    int epochMillis?;
    # Date in the format used in the Jira REST APIs, which is ISO8601 format but extended with milliseconds. For example, 2016-09-28T23:08:32.097+1000
    string jira?;
|};

# A page of user results
public type PagedDTOUserDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    UserDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# SLA metric of a customer request, with its ongoing and completed cycles
public type SlaInformationDTO record {|
    # Format in which SLA is to be displayed in the UI
    string slaDisplayFormat?;
    # Details of the active cycle for the SLA
    SlaInformationOngoingCycleDTO ongoingCycle?;
    # REST API URL for the SLA
    @jsondata:Name {value: "_links"}
    SelfLinkDTO links?;
    # List of completed cycles for the SLA
    SlaInformationCompletedCycleDTO[] completedCycles?;
    # Description of the SLA
    string name?;
    # ID of the Service Level Agreement (SLA)
    string id?;
|};

# Represents the Queries record for the operation: getRequestTypeGroups
public type GetRequestTypeGroupsQueries record {
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# A file uploaded as a temporary attachment
public type TemporaryAttachment record {
    # Name of the uploaded file
    string fileName?;
    # ID of the temporary attachment, used to attach it to a request
    string temporaryAttachmentId?;
};

# Represents the Queries record for the operation: inviteCustomer
public type InviteCustomerQueries record {
    # Optional boolean flag to return 409 Conflict status code when a customer with the same email already exists
    boolean strictConflictStatusCode?;
};

# A completed cycle of an SLA metric
public type SlaInformationCompletedCycleDTO record {|
    # Duration within which the service should have been completed
    DurationDTO goalDuration?;
    # Time and date at which the SLA cycle breached in case of completed breached cycle or would have breached in case of non-breached completed cycle
    DateDTO breachTime?;
    # Indicates if the SLA (duration) was exceeded (true) or not (false)
    boolean breached?;
    # Time and date at which the SLA cycle started
    DateDTO startTime?;
    # Time and date at which the SLA cycle completed
    DateDTO stopTime?;
    # Duration in which the service was completed
    DurationDTO elapsedTime?;
    # Duration remaining after the service was completed
    DurationDTO remainingTime?;
|};

# A single validation error reported for a form
public type FormValidationErrorDTO record {|
    # Machine-readable validation error code
    string code?;
    # Identifies the form entity that caused the validation error
    FormValidationErrorContextDTO[] context?;
    # Detailed validation error message
    string detail?;
    # Short summary of the validation error
    string title?;
    # The HTTP status code
    int:Signed32 status?;
|};

# A request type of a service desk
public type RequestTypeDTO record {|
    # The request type's practice
    string practice?;
    # Help text for the request type
    string helpText?;
    # ID of the service desk the request type belongs to
    string serviceDeskId?;
    # REST API URL for the request type
    @jsondata:Name {value: "_links"}
    SelfLinkDTO links?;
    # Links to the request type's icons
    RequestTypeIconDTO icon?;
    # Description of the request type
    string description?;
    # Whether the user has permission to create a request with this request type
    boolean canCreateRequest?;
    # ID of the issue type the request type is based upon
    string issueTypeId?;
    # List of the request type groups the request type belongs to
    string[] groupIds?;
    # ID of the customer portal associated with the service desk project
    string portalId?;
    # List of items that can be expanded in the response by specifying the expand query parameter
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Short name for the request type
    string name?;
    # ID for the request type
    string id?;
    # Fields and additional metadata for creating a request that uses the request type
    CustomerRequestCreateMetaDTO fields?;
    # Whether request type is restricted or not
    "OPEN"|"RESTRICTED" restrictionStatus?;
|};

# Permissions the user holds on a request type
public type RequestTypePermissionCheckResponse record {|
    # List of request type IDs for which the user has permission to administer
    int:Signed32[] canAdminister?;
    # List of request type IDs for which the user can create requests
    int:Signed32[] canCreateRequest?;
|};

# Details of the operations that can be performed on the issue
public type Operations record {
    # Details of the link groups defining issue operations.
    LinkGroup[] linkGroups?;
};

# Represents the Queries record for the operation: getServiceDesks
public type GetServiceDesksQueries record {
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig|http:CredentialsConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# A workflow transition available to the customer on a request
public type CustomerTransitionDTO record {|
    # Name of the transition
    string name?;
    # ID of the transition
    string id?;
|};

# Details of user or system associated with a issue history metadata item
public type HistoryMetadataParticipant record {
    # The URL to an avatar for the user or system associated with a history record.
    string avatarUrl?;
    # The display name of the user or system associated with a history record.
    string displayName?;
    # The key of the display name of the user or system associated with a history record.
    string displayNameKey?;
    # The ID of the user or system associated with a history record.
    string id?;
    # The type of the user or system associated with a history record.
    string 'type?;
    # The URL of the user or system associated with a history record.
    string url?;
};

# Represents the Queries record for the operation: getCustomers
public type GetCustomersQueries record {
    # The string used to filter the customer list
    string query?;
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of users to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# Represents the Headers record for the operation: attachTemporaryFile
public type AttachTemporaryFileHeaders record {
    # XSRF protection bypass that Jira requires on multipart requests. Must be `no-check`
    @http:Header {name: "X-Atlassian-Token"}
    string xAtlassianToken = "no-check";
};

# Version and build information about the Jira Service Management instance
public type SoftwareInfoDTO record {|
    # REST API URL of the instance
    @jsondata:Name {value: "_links"}
    SelfLinkDTO links?;
    # Reference of the change set included in the build
    string buildChangeSet?;
    # Indicates whether the instance is licensed (true) or not (false)
    boolean isLicensedForUse?;
    # Jira Platform version upon which Service Desk is based
    string platformVersion?;
    # Date of the current build
    DateDTO buildDate?;
    # Jira Service Management version
    string version?;
|};

# Represents the Queries record for the operation: getInsightWorkspaces
public type GetInsightWorkspacesQueries record {
    # The starting index of the returned objects. Base index: 0
    int:Signed32 'start = 0;
    # The maximum number of objects to return per page
    int:Signed32 'limit = 50;
};

# Decision to record against an approval
public type ApprovalDecisionRequestDTO record {|
    # Response to the approval request
    "approve"|"decline" decision?;
|};

# A Jira Service Management organization
public type OrganizationDTO record {|
    # REST API URL to the organization
    @jsondata:Name {value: "_links"}
    SelfLinkDTO links?;
    # Date the organization was created. This field may not be present in some older organizations
    DateDTO created?;
    # Name of the organization
    string name?;
    # A unique system generated ID for the organization
    string id?;
    # Returns if an organization is managed by scim. This field may not be present in some older organizations
    boolean scimManaged?;
    # A unique system generated ID for the organization. This is identity from the group directory id
    string uuid?;
|};

# Represents the Queries record for the operation: getRequestComments
public type GetRequestCommentsQueries record {
    # Specifies whether to return internal comments or not. Default: true
    boolean internal?;
    # A multi-value parameter indicating which properties of the comment to expand:
    # 
    #  *  `attachment` returns the attachment details, if any, for each comment. (If you want to get all attachments for a request, use [servicedeskapi/request/\{issueIdOrKey\}/attachment](#api-request-issueIdOrKey-attachment-get).)
    #  *  `renderedBody` (Experimental) returns the rendered body in HTML format (in addition to the raw body) for each comment
    string[] expand?;
    # Specifies whether to return public comments or not. Default: true
    boolean 'public?;
    # The starting index of the returned comments. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of comments to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# A page of sla information results
public type PagedDTOSlaInformationDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    SlaInformationDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Represents the Queries record for the operation: getCustomerRequestByIdOrKey
public type GetCustomerRequestByIdOrKeyQueries record {
    # A multi-value parameter indicating which properties of the customer request to expand, where:
    # 
    #  *  `serviceDesk` returns additional service desk details.
    #  *  `requestType` returns additional customer request type details.
    #  *  `participant` returns the participant details.
    #  *  `sla` returns the SLA information.
    #  *  `status` returns the status transitions, in chronological order.
    #  *  `attachment` returns the attachments.
    #  *  `action` returns the actions that the user can or cannot perform.
    #  *  `comment` returns the comments.
    #  *  `comment.attachment` returns the attachment details for each comment.
    #  *  `comment.renderedBody` (Experimental) return the rendered body in HTML format (in addition to the raw body) for each comment
    string[] expand?;
};

# Details of a request type to create
public type RequestTypeCreateDTO record {|
    # ID of the request type to add to the service desk
    string issueTypeId?;
    # Help text for the request type on the service desk
    string helpText?;
    # Name of the request type on the service desk
    string name?;
    # Description of the request type on the service desk
    string description?;
|};

# Represents the Queries record for the operation: getCustomerRequestStatus
public type GetCustomerRequestStatusQueries record {
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# Represents the Queries record for the operation: getUsersInOrganization
public type GetUsersInOrganizationQueries record {
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of users to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# Represents the Queries record for the operation: getRequestParticipants
public type GetRequestParticipantsQueries record {
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of request types to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# Request types and permissions to check for a user
public type RequestTypePermissionCheckRequestDTO record {|
    # The account ID of a user
    string accountId?;
    # List of requested permissions
    ("canCreateRequest"|"canAdminister")[] permissions?;
    # List of request type IDs
    int:Signed32[] requestTypeIds?;
|};

# A page of attachment results
public type PagedDTOAttachmentDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    AttachmentDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Represents the Queries record for the operation: getCommentAttachments
public type GetCommentAttachmentsQueries record {
    # The starting index of the returned comments. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of comments to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# Pagination links of a paged response
public type PagedLinkDTO record {|
    # REST API URL for the next page, if there is one
    string next?;
    # REST API URL for the previous page, if there is one
    string prev?;
    # Context path of the paged resource
    string context?;
    # REST API URL for the current page
    string self?;
    # Base URL for the REST API calls
    string base?;
|};

# Links to the images of a request type icon
public type RequestTypeIconLinkDTO record {|
    # URLs for the request type icons
    record {|string...;|} iconUrls?;
|};

# Links to a customer request in the agent view, the portal and the REST API
public type CustomerRequestLinkDTO record {|
    # Jira agent view URL for the request
    string agent?;
    # REST API URL for the request
    string jiraRest?;
    # Web URL for the request
    string web?;
    # REST API URL of the customer request
    string self?;
|};

# A status of a customer request and when it was set
public type CustomerRequestStatusDTO record {|
    # Date on which the status was attained
    DateDTO statusDate?;
    # Status category the status belongs to
    "UNDEFINED"|"NEW"|"INDETERMINATE"|"DONE" statusCategory?;
    # Name of the status condition
    string status?;
|};

# Customer satisfaction (CSAT) feedback on a request
public type CSATFeedbackFullDTO record {|
    # A numeric representation of the rating, this must be an integer value between 1 and 5
    int:Signed32 rating?;
    # (Optional) The comment provided with this feedback
    AdditionalCommentDTO comment?;
    # Indicates the type of feedback, supported values: `csat`
    string 'type?;
|};

# A page of comment results
public type PagedDTOCommentDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    CommentDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Details of a customer to create
public type CustomerCreateDTO record {|
    # Customer's name for display in the UI
    string displayName?;
    # Deprecated, please use 'displayName'
    string fullName?;
    # Customer's email address
    string email?;
|};

# A comment on a customer request
public type CommentDTO record {|
    # The rendered body of the comment
    RenderedValueDTO renderedBody?;
    # List of the attachments included in the comment
    PagedDTOAttachmentDTO attachments?;
    # Indicates whether the comment is public (true) or private/internal (false)
    boolean 'public?;
    # REST API URL link to the comment
    @jsondata:Name {value: "_links"}
    SelfLinkDTO links?;
    # Details of the customer who authored the comment
    UserDTO author?;
    # Date the comment was created
    DateDTO created?;
    # List of items that can be expanded in the response by specifying the expand query parameter
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # ID of the comment
    string id?;
    # Content of the comment
    string body?;
|};

# A page of queue results
public type PagedDTOQueueDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    QueueDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Organization to add to or remove from a service desk
public type OrganizationServiceDeskUpdateDTO record {
    # List of organizations, specified by 'ID' field values, to add to or remove from the service desk.
    int:Signed32 organizationId;
    # Service desk Id for which, organization needs to be updated
    string serviceDeskId?;
};

# A change item
public type ChangeDetails record {|
    # The name of the field changed
    string 'field?;
    # The details of the original value
    string 'from?;
    # The details of the new value as a string
    string toString?;
    # The details of the original value as a string
    string fromString?;
    # The details of the new value
    string to?;
    # The type of the field changed
    string fieldtype?;
    # The ID of the field changed
    string fieldId?;
|};

# Location of the rendered content of a knowledge base article
public type ContentDTO record {|
    # Url containing the body of the article (without title), suitable for rendering in an iframe
    string iframeSrc?;
|};

# An entity property, for more information see [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/)
public type EntityProperty record {|
    # The value of the property. Required on create and update
    anydata value?;
    # The key of the property. Required on create and update
    string 'key?;
|};

# Represents the Queries record for the operation: getOrganizations
public type GetOrganizationsQueries record {
    # The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*
    string accountId?;
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of organizations to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# An attachment on a customer request
public type AttachmentDTO record {|
    # Filename of the item attached
    string filename?;
    # Size of the attachment in bytes
    int size?;
    # Various URLs for the attachment
    @jsondata:Name {value: "_links"}
    AttachmentLinkDTO links?;
    # Details of the user who attached the file
    UserDTO author?;
    # Date the attachment was added
    DateDTO created?;
    # MIME type of the attachment
    string mimeType?;
|};

# A status category
public type StatusCategory record {
    # The name of the color used to represent the status category.
    string colorName?;
    # The ID of the status category.
    int id?;
    # The key of the status category.
    string 'key?;
    # The name of the status category.
    string name?;
    # The URL of the status category.
    string self?;
};

# Temporary attachments to add to a request, with an optional comment
public type AttachmentCreateDTO record {|
    # List of IDs for the temporary attachments to be added to the customer request
    string[] temporaryAttachmentIds?;
    # Controls whether the comment and its attachments are visible to customers
    boolean 'public?;
    # Additional content of the comment
    AdditionalCommentDTO additionalComment?;
|};

# A page of request type group results
public type PagedDTORequestTypeGroupDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    RequestTypeGroupDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# A page of customer request results
public type PagedDTOCustomerRequestDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    CustomerRequestDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# A log of changes made to issue fields. Changelogs related to workflow associations are currently being deprecated
public type Changelog record {|
    # The history metadata associated with the changed
    HistoryMetadata historyMetadata?;
    # The user who made the change
    UserDetails author?;
    # The date on which the change took place
    string created?;
    # The ID of the changelog
    string id?;
    # The list of items changed
    ChangeDetails[] items?;
|};

# An approval on a customer request
public type ApprovalDTO record {|
    # Date the approval was created
    DateDTO createdDate?;
    # The REST API URL of the approval
    @jsondata:Name {value: "_links"}
    SelfLinkDTO links?;
    # Indicates whether the user making the request is one of the approvers and can respond to the approval (true) or not (false)
    boolean canAnswerApproval?;
    # Description of the approval being sought or provided
    string name?;
    # Detailed list of the users who must provide a response to the approval
    ApproverDTO[] approvers?;
    # Outcome of the approval, based on the approvals provided by all approvers
    "approved"|"declined"|"pending" finalDecision?;
    # ID of the approval
    string id?;
    # Date the approval was completed
    DateDTO completedDate?;
|};

# A queue of a service desk
public type QueueDTO record {|
    # JQL query that filters reqeusts for the queue
    string jql?;
    # REST API URL to the queue
    @jsondata:Name {value: "_links"}
    SelfLinkDTO links?;
    # Short name for the queue
    string name?;
    # ID for the queue
    string id?;
    # Fields returned for each request in the queue
    string[] fields?;
    # The count of customer requests in the queue
    int issueCount?;
|};

# A duration in milliseconds and in a human-readable form
public type DurationDTO record {|
    # Duration in a user-friendly text format
    string friendly?;
    # Duration in milliseconds
    int millis?;
|};

# Represents the Queries record for the operation: getSlaInformation
public type GetSlaInformationQueries record {
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of request types to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# Customers to add to or remove from a service desk
public type ServiceDeskCustomerDTO record {|
    # List of users, specified by account IDs, to add to or remove from a service desk
    string[] accountIds?;
    # This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. Use `accountIds` instead
    string[] usernames?;
|};

# Details about an issue
public type IssueBean record {|
    # The schema describing each field present on the issue
    record {|JsonTypeBean...;|} schema?;
    # The metadata for the fields on the issue that can be amended
    IssueUpdateMetadata editmeta?;
    # Fields to include in the issue response
    IncludedFields fieldsToInclude?;
    # Details of changelogs associated with the issue
    PageOfChangelogs changelog?;
    # The transitions that can be performed on the issue
    IssueTransition[] transitions?;
    # The rendered value of each field present on the issue
    record {} renderedFields?;
    # Expand options that include additional issue details in the response
    string expand?;
    # The ID and name of each field present on the issue
    record {|string...;|} names?;
    # The operations that can be performed on the issue
    Operations operations?;
    # The versions of each field on the issue
    record {|record {}...;|} versionedRepresentations?;
    # The URL of the issue details
    string self?;
    # The ID of the issue
    string id?;
    # Issue fields, keyed by field ID
    record {} fields?;
    # The key of the issue
    string 'key?;
    # Details of the issue properties identified in the request
    record {} properties?;
|};

# Represents the Queries record for the operation: getAttachmentsForRequest
public type GetAttachmentsForRequestQueries record {
    # The starting index of the returned attachment. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start = 0;
    # The maximum number of comments to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit = 50;
};

# Transition to perform on a customer request, with an optional comment
public type CustomerTransitionExecutionDTO record {|
    # ID of the transition to be performed
    string id?;
    # Comment explaining the reason for the transition
    AdditionalCommentDTO additionalComment?;
|};

# Details of an issue transition
public type IssueTransition record {
    # Expand options that include additional transition details in the response.
    string expand?;
    # Details of the fields associated with the issue transition screen. Use this information to populate `fields` and `update` in a transition request.
    record {|FieldMetadata...;|} fields?;
    # Whether there is a screen associated with the issue transition.
    boolean hasScreen?;
    # The ID of the issue transition. Required when specifying a transition to undertake.
    string id?;
    # Whether the transition is available to be performed.
    boolean isAvailable?;
    # Whether the issue has to meet criteria before the issue transition is applied.
    boolean isConditional?;
    # Whether the issue transition is global, that is, the transition is applied to issues regardless of their status.
    boolean isGlobal?;
    # Whether this is the initial issue transition for the workflow.
    boolean isInitial?;
    # Whether the transition loops back to the same status
    boolean looped?;
    # The name of the issue transition.
    string name?;
    # Details of the issue status after the transition.
    StatusDetails to?;
};

# The ongoing cycle of an SLA metric
public type SlaInformationOngoingCycleDTO record {|
    # Indicates whether the SLA is paused (true) or not (false)
    boolean paused?;
    # Duration within which the service should be completed
    DurationDTO goalDuration?;
    # Time and date at which the SLA cycle would have breached its limit
    DateDTO breachTime?;
    # Indicates whether the SLA has been breached (true) or not (false)
    boolean breached?;
    # Time and date at which the SLA cycle started
    DateDTO startTime?;
    # Indicates whether the SLA it timed during calendared working hours only (true) or not (false)
    boolean withinCalendarHours?;
    # Duration of the service
    DurationDTO elapsedTime?;
    # Duration remaining in which to complete the service
    DurationDTO remainingTime?;
|};

# A page of customer transition results
public type PagedDTOCustomerTransitionDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    CustomerTransitionDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Represents the Queries record for the operation: getArticles
public type GetArticlesQueries record {
    # Pointer to a set of search results, returned as part of the next or prev URL from the previous search call
    string cursor?;
    # If set to true matching query term in the title and excerpt will be highlighted using the `@@@hl@@@term@@@endhl@@@` syntax. Default: false
    boolean highlight = false;
    # The string used to filter the articles (required)
    string query;
    # Should navigate to the previous page. Defaulted to false. Set to true as part of prev URL from the previous search call
    boolean prev = false;
    # (Deprecated) The starting index of the returned objects. Base index: 0
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50
    int:Signed32 'limit?;
};

# A page of assets workspace results
public type PagedDTOAssetsWorkspaceDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    AssetsWorkspaceDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Represents the Queries record for the operation: getRequestCommentById
public type GetRequestCommentByIdQueries record {
    # A multi-value parameter indicating which properties of the comment to expand:
    # 
    #  *  `attachment` returns the attachment details, if any, for the comment. (If you want to get all attachments for a request, use [servicedeskapi/request/\{issueIdOrKey\}/attachment](#api-request-issueIdOrKey-attachment-get).)
    #  *  `renderedBody` (Experimental) returns the rendered body in HTML format (in addition to the raw body) of the comment
    string[] expand?;
};

# Represents the Queries record for the operation: getRequestTypeById
public type GetRequestTypeByIdQueries record {
    # Comma-separated list of entities to expand in the response
    string[] expand?;
};

# A project category
public type UpdatedProjectCategory record {|
    # The description of the project category
    string name?;
    # The name of the project category
    string description?;
    # The URL of the project category
    string self?;
    # The ID of the project category
    string id?;
|};

# Property key details
public type PropertyKey record {|
    # The URL of the property
    string self?;
    # The key of the property
    string 'key?;
|};

# Fields included in or excluded from an issue response
public type IncludedFields record {|
    # Fields explicitly excluded from the response
    string[] excluded?;
    # Fields actually included in the response
    string[] actuallyIncluded?;
    # Fields explicitly requested in the response
    string[] included?;
|};

# Details of a comment to add to a request
public type CommentCreateDTO record {|
    # Indicates whether the comment is public (true) or private/internal (false)
    boolean 'public?;
    # Content of the comment
    string body?;
|};

# The metadata describing an issue field
public type FieldMetadata record {|
    # The list of values allowed in the field
    anydata[] allowedValues?;
    # Whether the field has a default value
    boolean hasDefaultValue?;
    # The data type of the field
    JsonTypeBean schema;
    # The list of operations that can be performed on the field
    string[] operations;
    # The configuration properties
    record {} configuration?;
    # The default value of the field
    anydata defaultValue?;
    # The name of the field
    string name;
    # The URL that can be used to automatically complete the field
    string autoCompleteUrl?;
    # The key of the field
    string 'key;
    # Whether the field is required
    boolean required;
|};

# A page of changelogs
public type PageOfChangelogs record {|
    # The number of results on the page
    int:Signed32 total?;
    # The maximum number of results that could be on the page
    int:Signed32 maxResults?;
    # The list of changelogs
    Changelog[] histories?;
    # The index of the first item returned on the page
    int:Signed32 startAt?;
|};

# Details of issue history metadata
public type HistoryMetadata record {
    # The activity described in the history record.
    string activityDescription?;
    # The key of the activity described in the history record.
    string activityDescriptionKey?;
    # Details of the user whose action created the history record.
    HistoryMetadataParticipant actor?;
    # Details of the cause that triggered the creation the history record.
    HistoryMetadataParticipant cause?;
    # The description of the history record.
    string description?;
    # The description key of the history record.
    string descriptionKey?;
    # The description of the email address associated the history record.
    string emailDescription?;
    # The description key of the email address associated the history record.
    string emailDescriptionKey?;
    # Additional arbitrary information about the history record.
    record {|string...;|} extraData?;
    # Details of the system that generated the history record.
    HistoryMetadataParticipant generator?;
    # The type of the history record.
    string 'type?;
};

# The value of a field on a customer request
public type CustomerRequestFieldValueDTO record {|
    # Value of the field rendered in the UI
    record {} renderedValue?;
    # Text label for the field
    string label?;
    # Value of the field
    anydata value?;
    # ID of the field
    string fieldId?;
|};

# A Jira user
public type UserDTO record {|
    # The accountId of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*
    string accountId?;
    # Customer's email address. Depending on the customer’s privacy settings, this may be returned as null
    string emailAddress?;
    # URLs for the customer record and related items
    @jsondata:Name {value: "_links"}
    UserLinkDTO links?;
    # Customer's name for display in a UI. Depending on the customer’s privacy settings, this may return an alternative value
    string displayName?;
    # This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details
    string name?;
    # Indicates if the customer is active (true) or inactive (false)
    boolean active?;
    # Customer time zone. Depending on the customer’s privacy settings, this may be returned as null
    string timeZone?;
    # This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details
    string 'key?;
|};

# A knowledge base article
public type ArticleDTO record {|
    # Source of the article
    SourceDTO 'source?;
    # Excerpt of the article which matches the given query string
    string excerpt?;
    # Title of the article
    string title?;
    # Location of the rendered article content
    ContentDTO content?;
|};

# Represents the Queries record for the operation: getQueues
public type GetQueuesQueries record {
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
    # Specifies whether to include each queue's customer request (issue) count in the response
    boolean includeCount = false;
};

# A page of insight workspace results
public type PagedDTOInsightWorkspaceDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    InsightWorkspaceDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Source of a knowledge base article
public type SourceDTO record {
    # Type of the knowledge base source
    "confluence" 'type?;
};

# User details permitted by the user's Atlassian Account privacy settings. However, be aware of these exceptions:
# 
#  *  User record deleted from Atlassian: This occurs as the result of a right to be forgotten request. In this case, `displayName` provides an indication and other parameters have default values or are blank (for example, email is blank).
#  *  User record corrupted: This occurs as a results of events such as a server import and can only happen to deleted users. In this case, `accountId` returns *unknown* and all other parameters have fallback values.
#  *  User record unavailable: This usually occurs due to an internal service outage. In this case, all parameters have fallback values
public type UserDetails record {|
    # The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*
    @constraint:String {maxLength: 128}
    string accountId?;
    # The email address of the user. Depending on the user’s privacy settings, this may be returned as null
    string emailAddress?;
    # The avatars of the user
    AvatarUrlsBean avatarUrls?;
    # The display name of the user. Depending on the user’s privacy settings, this may return an alternative value
    string displayName?;
    # The type of account represented by this user. This will be one of 'atlassian' (normal users), 'app' (application user) or 'customer' (Jira Service Desk customer user)
    string accountType?;
    # This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details
    string name?;
    # Whether the user is active
    boolean active?;
    # The URL of the user
    string self?;
    # The time zone specified in the user's profile. Depending on the user’s privacy settings, this may be returned as null
    string timeZone?;
    # This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details
    string 'key?;
|};

# Details about the operations available in this version
public type SimpleLink record {|
    # Sort weight of the link
    int:Signed32 weight?;
    # Target URL of the link
    string href?;
    # ID of the link
    string id?;
    # Display label of the link
    string label?;
    # CSS style class of the link
    string styleClass?;
    # Title (tooltip) of the link
    string title?;
    # CSS class of the link icon
    string iconClass?;
|};

# The HTML rendering of a field value
public type RenderedValueDTO record {|
    # HTML rendering of the field value
    string html?;
|};

# A page of article results
public type PagedDTOArticleDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    ArticleDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# A page of issue bean results
public type PagedDTOIssueBean record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    IssueBean[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Result of validating a customer request before it is created
public type RequestValidationResultDTO record {|
    # True when the payload is both structurally and semantically valid and safe to create
    boolean valid?;
    # General validation errors that are not attributable to a single field. Empty when valid
    string[] errorMessages?;
    # A machine-readable reason key categorising the overall failure. Null when valid
    string reasonKey?;
    # Field-level validation errors, keyed by the failing request field id. Empty when valid
    RequestFieldValidationErrorDTO[] fieldErrors?;
    # A single, human-readable summary describing why validation failed. Null when valid
    string errorMessage?;
    # ProForma form validation errors, if a form was supplied. Empty when valid or no form was present
    FormValidationErrorDTO[] formErrors?;
|};

# Represents the Queries record for the operation: getOrganizationsByServiceDeskId
public type GetOrganizationsByServiceDeskIdQueries record {
    # The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*
    string accountId?;
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# A page of customer request status results
public type PagedDTOCustomerRequestStatusDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    CustomerRequestStatusDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Details of an organization to create
public type OrganizationCreateDTO record {|
    # Name of the organization. Must contain 1-200 characters
    string name;
|};

# Represents the Queries record for the operation: getCustomerTransitions
public type GetCustomerTransitionsQueries record {
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# A service desk
public type ServiceDeskDTO record {|
    # Key of the peer project of the service desk
    string projectKey?;
    # REST API URL to the service desk
    @jsondata:Name {value: "_links"}
    SelfLinkDTO links?;
    # ID of the service desk
    string id?;
    # Name of the project and service desk
    string projectName?;
    # ID of the peer project for the service desk
    string projectId?;
    # Key of the project type
    string projectTypeKey?;
|};

# Details of an insight workspace ID
public type InsightWorkspaceDTO record {|
    # The workspace ID used as the identifier to access the Insight REST API
    string workspaceId?;
|};

# Participants to add to or remove from a request
public type RequestParticipantUpdateDTO record {|
    # List of users, specified by account IDs, to add to or remove as participants in the request
    string[] accountIds?;
    # This property is no longer available and will be removed from the documentation soon. See the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details. Use `accountIds` instead
    string[] usernames?;
|};

# A group of request types in a service desk portal
public type RequestTypeGroupDTO record {|
    # Name of the request type group
    string name?;
    # ID of the request type group
    string id?;
|};

# The icon of a request type
public type RequestTypeIconDTO record {|
    # Map of the URLs for the request type icons
    @jsondata:Name {value: "_links"}
    RequestTypeIconLinkDTO links?;
    # ID of the request type icon
    string id?;
|};

# URLs of a user avatar in different sizes
public type AvatarUrlsBean record {|
    # The URL of the item's 48x48 pixel avatar
    @jsondata:Name {value: "48x48"}
    string param48x48?;
    # The URL of the item's 24x24 pixel avatar
    @jsondata:Name {value: "24x24"}
    string param24x24?;
    # The URL of the item's 16x16 pixel avatar
    @jsondata:Name {value: "16x16"}
    string param16x16?;
    # The URL of the item's 32x32 pixel avatar
    @jsondata:Name {value: "32x32"}
    string param32x32?;
|};

# Represents the Queries record for the operation: getCustomerRequests
public type GetCustomerRequestsQueries record {
    # Filters results to customer requests based on their approval status:
    # 
    #  *  `MY_PENDING_APPROVAL` returns customer requests pending the user's approval.
    #  *  `MY_HISTORY_APPROVAL` returns customer requests where the user was an approver.
    # 
    # **Note**: Valid only when used with requestOwnership=APPROVER
    string approvalStatus?;
    # Filters customer requests that belong to a specific organization (note that the user must be a member of that organization). **Note**: Valid only when used with requestOwnership=ORGANIZATION
    int:Signed32 organizationId?;
    # A multi-value parameter indicating which properties of the customer request to expand, where:
    # 
    #  *  `serviceDesk` returns additional details for each service desk.
    #  *  `requestType` returns additional details for each request type.
    #  *  `participant` returns the participant details, if any, for each customer request.
    #  *  `sla` returns the SLA information on each customer request.
    #  *  `status` returns the status transitions, in chronological order, for each customer request.
    #  *  `attachment` returns the attachments for the customer request.
    #  *  `action` returns the actions that the user can or cannot perform on this customer request.
    #  *  `comment` returns the comments, if any, for each customer request.
    #  *  `comment.attachment` returns the attachment details, if any, for each comment.
    #  *  `comment.renderedBody` (Experimental) returns the rendered body in HTML format (in addition to the raw body) for each comment
    string[] expand?;
    # Filters customer requests where the request summary matches the `searchTerm`. [Wildcards](https://confluence.atlassian.com/display/JIRACORECLOUD/Search+syntax+for+text+fields) can be used in the `searchTerm` parameter
    string searchTerm?;
    # Filters customer requests using the following values:
    # 
    #  *  `OWNED_REQUESTS` returns customer requests where the user is the creator.
    #  *  `PARTICIPATED_REQUESTS` returns customer requests where the user is a participant.
    #  *  `ORGANIZATION` returns customer requests for an organization of which the user is a member when used in conjunction with `organizationId`.
    #  *  `ALL_ORGANIZATIONS` returns customer requests that belong to all organizations of which the user is a member.
    #  *  `APPROVER` returns customer requests where the user is an approver. Can be used in conjunction with `approvalStatus` to filter pending or complete approvals.
    #  *  `ALL_REQUESTS` returns all customer requests. **Deprecated and will be removed, as the returned requests may change if more values are added in the future. Instead, explicitly list the desired filtering strategies.**
    # 
    # Multiple values of the query parameter are supported. For example, `requestOwnership=OWNED_REQUESTS&requestOwnership=PARTICIPATED_REQUESTS` will only return customer requests where the user is the creator or a participant. If not specified, filtering defaults to `OWNED_REQUESTS`, `PARTICIPATED_REQUESTS`, and `ALL_ORGANIZATIONS`
    string[] requestOwnership?;
    # Filters customer requests by service desk
    int:Signed32 serviceDeskId?;
    # Filters customer requests by request type. Note that the `serviceDeskId` must be specified for the service desk in which the request type belongs
    int:Signed32 requestTypeId?;
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
    # Filters customer requests where the request is closed, open, or either of the two where:
    # 
    #  *  `CLOSED_REQUESTS` returns customer requests that are closed.
    #  *  `OPEN_REQUESTS` returns customer requests that are open.
    #  *  `ALL_REQUESTS` returns all customer requests
    string requestStatus?;
};

# Whether the user is subscribed to notifications for a request
public type RequestNotificationSubscriptionDTO record {|
    # Indicates whether the user is subscribed (true) or not (false) to the request's notifications
    boolean subscribed?;
|};

# List of property keys
public type PropertyKeys record {|
    # Property key details
    PropertyKey[] keys?;
|};

# A comment to add alongside another action
public type AdditionalCommentDTO record {|
    # Content of the comment
    string body?;
|};

# A field of a request type
public type RequestTypeFieldDTO record {|
    # Whether the field is shown on the portal
    boolean visible?;
    # Name of the field
    string name?;
    # List of default values for the field
    RequestTypeFieldValueDTO[] defaultValues?;
    # Description of the field
    string description?;
    # List of preset values for the field
    string[] presetValues?;
    # List of valid values for the field
    RequestTypeFieldValueDTO[] validValues?;
    # Jira specific implementation details for the field in the UI
    JsonTypeBean jiraSchema?;
    # Indicates if the field is required (true) or not (false)
    boolean required?;
    # ID of the field
    string fieldId?;
|};

# Details of a customer to invite to a service desk
public type ServiceDeskCustomerInviteDTO record {|
    # Customer's name for display in the UI
    string displayName?;
    # Customer's email address
    string email?;
|};

# Details of an issue status
public type StatusDetails record {
    # The description of the status.
    string description?;
    # The URL of the icon used to represent the status.
    string iconUrl?;
    # The ID of the status.
    string id?;
    # The name of the status.
    string name?;
    # The scope of the field.
    Scope scope?;
    # The URL of the status.
    string self?;
    # The category assigned to the status.
    StatusCategory statusCategory?;
};

# Represents the Queries record for the operation: getQueue
public type GetQueueQueries record {
    # Specifies whether to include each queue's customer request (issue) count in the response
    boolean includeCount = false;
};

# A customer request
public type CustomerRequestDTO record {|
    # Summary of the request created
    string summary?;
    # ID of the request, as the peer issue ID
    string issueId?;
    # List of attachments included with the request
    PagedDTOAttachmentDTO attachments?;
    # List of comments included with the request
    PagedDTOCommentDTO comments?;
    # Key of the request, as the peer issue key
    string issueKey?;
    # Expandable details of the request type
    RequestTypeDTO requestType?;
    # ID of the service desk the request belongs to
    string serviceDeskId?;
    # List of links associated with the request
    @jsondata:Name {value: "_links"}
    CustomerRequestLinkDTO links?;
    # Status of the request
    CustomerRequestStatusDTO currentStatus?;
    # ID of the request type for the request
    string requestTypeId?;
    # Expandable details of the service desk
    ServiceDeskDTO serviceDesk?;
    # Expandable details of the SLAs relating to the request
    PagedDTOSlaInformationDTO sla?;
    # Details of the customer reporting the request
    UserDTO reporter?;
    # JSON map of Jira field IDs and their values representing the content of the request. This list does not include hidden fields
    CustomerRequestFieldValueDTO[] requestFieldValues?;
    # Date on which the request was created
    DateDTO createdDate?;
    # List of items that can be expanded in the response by specifying the expand query parameter
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # List of actions that the user can take on the request
    CustomerRequestActionsDTO actions?;
    # Expandable details of the customers participating in the request
    PagedDTOUserDTO participants?;
    # Expandable details of the request's status history
    PagedDTOCustomerRequestStatusDTO status?;
|};

# Answers to a request type form, keyed by question ID
public type Form record {
    # JSON mapping of form field answers containing form field IDs and corresponding values.
    record {|FormAnswer...;|} answers?;
};

# A page of approval results
public type PagedDTOApprovalDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    ApprovalDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# Represents the Queries record for the operation: getRequestTypes
public type GetRequestTypesQueries record {
    # Comma-separated list of entities to expand in the response
    string[] expand?;
    # Filters results to those in a customer request type group
    int:Signed32 groupId?;
    # The string to be used to filter the results
    string searchQuery?;
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
    # Whether to include hidden request types when searching with `searchQuery`
    boolean includeHiddenRequestTypesInSearch = false;
    # Request type restriction status (`open` or `restricted`) used to filter the results
    string restrictionStatus?;
};

# A list of editable field details
public type IssueUpdateMetadata record {
    # Metadata of the editable fields, keyed by field ID
    record {|FieldMetadata...;|} fields?;
};

# Details a link group, which defines issue operations
public type LinkGroup record {|
    # Nested link groups
    LinkGroup[] groups?;
    # Header link of the group
    SimpleLink header?;
    # Sort weight of the group
    int:Signed32 weight?;
    # Links in the group
    SimpleLink[] links?;
    # ID of the link group
    string id?;
    # CSS style class of the group
    string styleClass?;
|};

# Represents the Queries record for the operation: getApprovals
public type GetApprovalsQueries record {
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of approvals to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# Details of a customer request to create
public type RequestCreateDTO record {|
    # List of customers to participate in the request, as a list of `accountId` values
    string[] requestParticipants?;
    # The `accountId` of the customer that the request is being raised on behalf of
    string raiseOnBehalfOf?;
    # Provides answers to the form associated with a request type. Omit Jira fields from `requestFieldValues` if they're linked to form answers. For form answers in ADF format, set `isAdfRequest` to true
    Form form?;
    # ID of the service desk in which to create the request
    string serviceDeskId?;
    # ID of the request type for the request
    string requestTypeId?;
    # (Experimental) Shows extra information for the request channel
    string channel?;
    # JSON map of Jira field IDs and their values representing the content of the request
    record {} requestFieldValues?;
    # (Experimental) Whether to accept rich text fields in Atlassian Document Format (ADF)
    boolean isAdfRequest?;
|};

# Temporary attachments created by an upload
public type TemporaryAttachments record {
    # The uploaded temporary attachments
    TemporaryAttachment[] temporaryAttachments?;
};

# Links to an attachment, its content and its thumbnail
public type AttachmentLinkDTO record {|
    # URL for the attachment's thumbnail image
    string thumbnail?;
    # REST API URL for the attachment
    string jiraRest?;
    # REST API URL of the attachment
    string self?;
    # URL for the attachment
    string content?;
|};

# Fields and options available when creating a request of a request type
public type CustomerRequestCreateMetaDTO record {|
    # Flag indicating if a request can be raised on behalf of another user (true) or not
    boolean canRaiseOnBehalfOf?;
    # Flag indicating if participants can be added to a request (true) or not
    boolean canAddRequestParticipants?;
    # List of the fields included in this request
    RequestTypeFieldDTO[] requestTypeFields?;
|};

# A validation error on a request field
public type RequestFieldValidationErrorDTO record {|
    # The id of the request field that failed validation (matches a key in 'requestFieldValues')
    string 'field?;
    # A human-readable explanation of why this field failed validation
    string message?;
|};

# Represents the Queries record for the operation: createCustomer
public type CreateCustomerQueries record {
    # Optional boolean flag to return 409 Conflict status code for duplicate customer creation request
    boolean strictConflictStatusCode?;
};

# Whether an action is allowed on a customer request
public type CustomerRequestActionDTO record {|
    # Indicates whether the user can undertake the action (true) or not (false)
    boolean allowed?;
|};

# Represents the Queries record for the operation: getAllRequestTypes
public type GetAllRequestTypesQueries record {
    # Comma-separated list of entities to expand in the response
    string[] expand?;
    # Filter the request types by service desk Ids provided. Multiple values of the query parameter are supported. For example, `serviceDeskId=1&serviceDeskId=2` will return request types only for service desks 1 and 2
    int:Signed32[] serviceDeskId?;
    # String to be used to filter the results
    string searchQuery?;
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
    # Whether to include hidden request types when searching with `searchQuery`
    boolean includeHiddenRequestTypesInSearch = false;
    # Request type restriction status (`open` or `restricted`) used to filter the results
    string restrictionStatus?;
};

# OAuth2 Refresh Token Grant Configs
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    # Refresh URL
    string refreshUrl = "https://auth.atlassian.com/oauth/token";
|};

# Represents the Queries record for the operation: getAssetsWorkspaces
public type GetAssetsWorkspacesQueries record {
    # The starting index of the returned workspace IDs. Base index: 0 See the [Pagination](#pagination) section for more details
    int:Signed32 'start = 0;
    # The maximum number of workspace IDs to return per page. Default: 50 See the [Pagination](#pagination) section for more details
    int:Signed32 'limit = 50;
};

# Attachments and comment created on a request
public type AttachmentCreateResultDTO record {|
    # List of the attachments added
    PagedDTOAttachmentDTO attachments?;
    # Details of the comment included with the attachments
    CommentDTO comment?;
|};

# Details of an Assets workspace ID
public type AssetsWorkspaceDTO record {|
    # The workspace ID used as the identifier to access the Assets REST API
    string workspaceId?;
|};

# Represents the Queries record for the operation: getArticlesByServiceDeskId
public type GetArticlesByServiceDeskIdQueries record {
    # Pointer to a set of search results, returned as part of the next or prev URL from the previous search call
    string cursor?;
    # If set to true matching query term in the title and excerpt will be highlighted using the `@@@hl@@@term@@@endhl@@@` syntax. Default: false
    boolean highlight = false;
    # The string used to filter the articles (required)
    string query;
    # Should navigate to the previous page. Defaulted to false. Set to true as part of prev URL from the previous search call
    boolean prev = false;
    # (Deprecated) The starting index of the returned objects. Base index: 0
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the section for more details
    int:Signed32 'limit?;
};

# Details about a project
public type ProjectDetails record {|
    # Whether or not the project is simplified
    boolean simplified?;
    # The URLs of the project's avatars
    AvatarUrlsBean avatarUrls?;
    # The category the project belongs to
    UpdatedProjectCategory projectCategory?;
    # The name of the project
    string name?;
    # The URL of the project details
    string self?;
    # The ID of the project
    string id?;
    # The [project type](https://confluence.atlassian.com/x/GwiiLQ#Jiraapplicationsoverview-Productfeaturesandprojecttypes) of the project
    "software"|"service_desk"|"business"|"product_discovery" projectTypeKey?;
    # The key of the project
    string 'key?;
|};

# Links to a user in the REST API and to their avatars
public type UserLinkDTO record {|
    # REST API URL for the customer
    string jiraRest?;
    # Links to the various sizes of the customer's avatar. Note that this property is deprecated, and will be removed in future versions
    record {|string...;|} avatarUrls?;
    # REST API URL of the user
    string self?;
|};

# A valid or preset value of a request type field
public type RequestTypeFieldValueDTO record {|
    # List of child fields
    RequestTypeFieldValueDTO[] children?;
    # Label for the field
    string label?;
    # Value of the field
    string value?;
|};

# An approver and their decision
public type ApproverDTO record {|
    # Details of the User who is providing approval
    UserDTO approver?;
    # Decision made by the approver
    "approved"|"declined"|"pending" approverDecision?;
|};

# Represents the Queries record for the operation: getIssuesInQueue
public type GetIssuesInQueueQueries record {
    # The starting index of the returned objects. Base index: 0. See the [Pagination](#pagination) section for more details
    int:Signed32 'start?;
    # The maximum number of items to return per page. Default: 50. See the [Pagination](#pagination) section for more details
    int:Signed32 'limit?;
};

# The schema of a field
public type JsonTypeBean record {|
    # If the field is a system field, the name of the field
    string system?;
    # If the field is a custom field, the configuration of the field
    record {} configuration?;
    # If the field is a custom field, the URI of the field
    string custom?;
    # The data type of the field
    string 'type;
    # If the field is a custom field, the custom ID of the field
    int customId?;
    # When the data type is an array, the name of the field items within the array
    string items?;
|};

# A page of service desk results
public type PagedDTOServiceDeskDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    ServiceDeskDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# A page of request type results
public type PagedDTORequestTypeDTO record {|
    # Number of items returned in the page
    int:Signed32 size?;
    # List of the links relating to the page
    @jsondata:Name {value: "_links"}
    PagedLinkDTO links?;
    # Indicates if this is the last page of records (true) or not (false)
    boolean isLastPage?;
    # Details of the items included in the page
    RequestTypeDTO[] values?;
    # Fields that can be expanded in the response
    @jsondata:Name {value: "_expands"}
    string[] expands?;
    # Number of items to be returned per page, up to the maximum set for these objects in the current implementation
    int:Signed32 'limit?;
    # Index of the first item returned in the page
    int:Signed32 'start?;
|};

# The projects the item is associated with. Indicated for items associated with [next-gen projects](https://confluence.atlassian.com/x/loMyO)
public type Scope record {
    # The project the item has scope in.
    ProjectDetails project?;
    # The type of scope.
    "PROJECT"|"TEMPLATE" 'type?;
};

# Context of a form validation error
public type FormValidationErrorContextDTO record {|
    # ID of the form entity related to the validation error
    string id?;
    # Type of form entity related to the validation error
    string 'type?;
|};

# Represents the Queries record for the operation: createCustomerSkipPermissionCheck
public type CreateCustomerSkipPermissionCheckQueries record {
    # Optional boolean flag; when \{@code true\}, returns 409 Conflict for duplicate email instead of the default 400
    boolean strictConflictStatusCode?;
};

# An answer to a form question
public type FormAnswer record {|
    # Answer in date format (yyyy-MM-dd)
    string date?;
    # Answer in Atlassian Document Format (ADF)
    JsonNode adf?;
    # The IDs of files to be attached to the form that are obtained by calling the ‘attach temporary file’ endpoint on the corresponding service desk
    string[] files?;
    # Answer in free text format
    string text?;
    # Answer in timestamp format (HH:mm)
    string time?;
    # IDs of selected choices
    string[] choices?;
    # IDs of selected users
    string[] users?;
|};
